[features]
seeds = true
skip-lint = false
[programs.localnet]
seahorse_auction = "DPzpTr7kZupCWD98LaWNTtXAMhv3qKX7w9CdG7bo5acS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/anoushkkharangate/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
